# 参考 https://github.com/marketplace/actions/build-and-push-docker-images

name: docker hub ci # 修改

on:
  push:
    branches:
      - 'master' # 修改

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm/v7 # 选择编译平台 linux/amd64 ; linux/arm/v7 ; linux/arm64
          push: true
          tags: duxlong/alddns:armv7 # 修改
